# Site settings
baseurl = ""
languageCode = "en-us"
title = "Zudo"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

[params]
	name = "haris (/kod)"
	description = "Blogger & Programmer"
	bio = "Blogger & Programmer"
	# Enter optionally your twitter account
	twitter = "Your Twitter account"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = "Feed"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = "Posts you might be interested"
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Broken As Designed, Caching Out."
	tweet = "Tweet"
	share = ""
	# 404 page
	title404 = "Not Available"
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/"
    github   = "https://www.github.com/"
    linkedin  = "https://www.linkedin.com/"
